# Standardized Rule Codes

# Grade Boundary Rules
GRADE_80_AND_ABOVE = "80_AND_ABOVE"
GRADE_70_TO_79 = "70_TO_79"
GRADE_60_TO_69 = "60_TO_69"
GRADE_50_TO_59 = "50_TO_59"
GRADE_40_TO_49 = "40_TO_49"
GRADE_33_TO_39 = "33_TO_39"
BELOW_33 = "BELOW_33"

# Practical Rules
PRACTICAL_DUAL_THRESHOLD = "PRACTICAL_DUAL_THRESHOLD"
THEORY_THRESHOLD_FAIL = "THEORY_THRESHOLD_FAIL"
PRACTICAL_THRESHOLD_FAIL = "PRACTICAL_THRESHOLD_FAIL"

# Optional Subject Rules
OPTIONAL_BONUS = "OPTIONAL_BONUS"
OPTIONAL_NO_CONTRIBUTION = "OPTIONAL_NO_CONTRIBUTION"
OPTIONAL_ABSENCE = "OPTIONAL_ABSENCE"

# Compulsory Override Rules
COMPULSORY_FAILURE = "COMPULSORY_FAILURE"
COMPULSORY_ABSENCE = "COMPULSORY_ABSENCE"

# GPA Cap Rules
GPA_CAP_5 = "GPA_CAP_5"
